# Generated by Django 5.2.6 on 2025-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='StepUp', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='navbar_logos/')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
            },
        ),
    ]
