# Generated by Django 5.2.6 on 2025-09-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
