# Generated by Django 5.2.6 on 2025-09-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usercheckoutdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercheckoutdetail',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='usercheckoutdetail',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='usercheckoutdetail',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='usercheckoutdetail',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='usercheckoutdetail',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usercheckoutdetail',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='usercheckoutdetail',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='usercheckoutdetail',
            name='payment_token',
            field=models.CharField(blank=True, help_text='Payment gateway token (if used).', max_length=255),
        ),
        migrations.AddField(
            model_name='usercheckoutdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usercheckoutdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usercheckoutdetail',
            index=models.Index(fields=['user'], name='core_userch_user_id_3169e6_idx'),
        ),
        migrations.AddIndex(
            model_name='usercheckoutdetail',
            index=models.Index(fields=['created'], name='core_userch_created_b8fb08_idx'),
        ),
    ]
