# Generated by Django 5.2.6 on 2025-09-18 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usercheckoutdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('dispatched', 'Order Dispatched'), ('in_transit', 'Order in transit'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=32)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='core.order')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
